#!/bin/bash
SHASHLIK_PATH=/opt/shashlik
export LD_LIBRARY_PATH=$SHASHLIK_PATH/lib64:$LD_LIBRARY_PATH
export PATH=$SHASHLIK_PATH/bin:$PATH

#copy user AVD stuff if needed.
#TODO phase this out by explicitly stating emulator paths rather than using AVD
#as this is clearly a bit of a hack
if [ ! -d ~/.android ]
then
    cp -R $SHASHLIK_PATH/useravd ~/.android
    chown -R $USER:$USER  ~/.android
fi

emulator64-x86 -avd AVD_for_Shahslik -no-boot-anim -verbose &

APK=$1

if [ -a ~/.local/share/shashlik/$APK.apk ]
then
    until adb -e  install -r ~/.local/share/shashlik/$APK.apk
    do
        echo waiting for startup
        sleep 1
    done
    rm ~/.local/share/shashlik/$APK.apk
fi

until adb -e shell monkey -p $APK -c android.intent.category.LAUNCHER 1
do
    echo waiting for startup
    sleep 1
done