#!/bin/bash
APK=$1
SHASHLIK_PATH=/opt/shashlik
SHASHLIK_USER_DIR=~/.local/share/shashlik
IMAGES_PATH=${SHASHLIK_PATH}/android
export LD_LIBRARY_PATH=$SHASHLIK_PATH/lib64:$LD_LIBRARY_PATH
export PATH=${SHASHLIK_PATH}/bin:${PATH}

mkdir -p ${SHASHLIK_USER_DIR}/system

emulator64-x86 \
    -sysdir ${IMAGES_PATH} \
    -system ${IMAGES_PATH}/system.img \
    -ramdisk ${IMAGES_PATH}/ramdisk.img \
    -kernel ${IMAGES_PATH}/kernel-qemu \
    -memory 512 \
    -data ${SHASHLIK_USER_DIR}/userdata.img \
    -datadir ${SHASHLIK_USER_DIR}/system \
    -noskin \
    -no-boot-anim \
    -verbose &

#-scale

if [ -a ~/.local/share/shashlik/$APK.apk ]
then
    until adb -e  install -r ~/.local/share/shashlik/$APK.apk
    do
        echo waiting for startup
        sleep 1
    done
    rm ~/.local/share/shashlik/$APK.apk
fi

until adb -e shell monkey -p $APK -c android.intent.category.LAUNCHER 1
do
    echo waiting for startup
    sleep 1
done